DM/urls.py
# from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    #    path('admin/', admin.site.urls),
    path('', include('App.urls'))
]

DM_admin/App/urls.py
from django.urls import path
from App import views
app_name = 'App'

urlpatterns = [
    path('', views.index, name='index'),
    # 左边导航栏
    path('left/',views.public_left, name='left'),

    # 右边的标题栏
    path('header/', views.public_header, name='header'),

    # 主窗口，内容展示
    path('main/',views.public_main, name='main'),
    path('main/<int:cid>/',views.public_main, name='main'),
    path('main/<int:cid>/<int:page>/',views.public_main, name='main2'),
    # 修改密码
    path("change_psw/", views.change_psw, name="change_psw.html"),
    # 修改用户信息
    path("change_user/<int:uid>", views.change_user, name="change_user.html"),
    # 登录
    path("loginb/", views.loginb, name='loginb.html'),
    # 退出
    path("login_out/", views.user_loginout, name='loginb.html'),

    # 用户管理页面
    path("tupian_pc_index/", views.tupian_pc_index, name="tupian_pc_index"),
    path("tupian_pc_index/<int:uid>/", views.tupian_pc_index, name="tupian_pc_index"),
    path("tupian_pc_index/<int:uid>/<int:page>", views.tupian_pc_index, name="tupian_pc_index"),

    # 评论设置页面
    path("xitong_set/", views.xitong_set, name='xitong_set'),
    path("xitong_set/<int:uid>/", views.xitong_set, name='xitong_set'),
    path("xitong_set/<int:uid>/<int:page>/", views.xitong_set, name='xitong_set'),

    path("public_super_cg/", views.public_super_cg, name='public_super_cg'),
    # 文章发布
    path("wenzhang_xinwen_fabu/", views.wenzhang_xinwen_fabu, name='wenzhang_xinwen_fabu'),
    # 添加评论
    path("add_mark/", views.add_mark, name='add_mark'),
    # 文章修改
    path("wenzhang_xinwen_xiugai/<int:aid>/<int:cid>/", views.wenzhang_xinwen_xiugai, name='wenzhang_xinwen_xiugai'),
    # 评论修改
    path("mark_xiugai/<int:mid>/<int:uid>/", views.mark_xiugai, name='mark_xiugai'),
    # 验证码
    path("get_verify_img",views.get_verify_img,name='get_verify_img'),

    #　注册用户
    path("user_register",views.user_register,name='user_register'),

    # 文件上传
    path("upload/",views.upload,name='upload'),

    # 文件删除
    path("delete/<int:aid>/<int:cid>/<int:page>/",views.del_article,name='del_article'),
    # 用户删除
    path("delete/<int:uid>/",views.del_user,name='del_user'),
    # 评论删除
    path("del_mark/<int:mid>/<int:uid>/<int:page>/", views.del_mark, name='del_mark'),

]

DM_admin/DM_admin/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('',include('App.urls'))
]

DM_admin/App/forms.py
# 用户自定义表单
from django import  forms
from django.core.exceptions import ValidationError
import re

from django.forms.utils import ErrorList

from App.models import User


class ChangePwdForm(forms.Form):
    oldpwd = forms.CharField(min_length=8,required=True,error_messages={'required':'旧密码必填','min_length':'最短8位'})
    newpwd = forms.CharField(min_length=8,required=True,error_messages={'required':'新密码必填','min_length':'最短8位'})
    cfmpwd = forms.CharField(min_length=8,required=True,error_messages={'required':'确认密码必填','min_length':'最短8位'})

    # 单字段验证(新密码校验)
    def clean_newpwd(self):
        newpwd = self.cleaned_data.get('newpwd')
        check = re.match(r'^(?![A-Za-z]+$)(?![A-Z\\d]+$)(?![A-Z\\W]+$)(?![a-z\\d]+$)(?![a-z\\W]+$)(?![\\d\\W]+$)',
                         newpwd)
        if check:
            return newpwd
        else:
            raise ValidationError({'newpwd':"数字、字母、符号组合，最少8个字符"})

    # 全局验证(一致性校验)
    def clean(self):
        newpwd = self.cleaned_data.get('newpwd')
        cfmpwd = self.cleaned_data.get('cfmpwd')
        print(newpwd,cfmpwd)
        if newpwd != cfmpwd:
            raise ValidationError({'cfmpwd':"您所输入密码与新密码不一致，请重新输入！"})
        return self.cleaned_data



    # def clean_oldpwd(self):
    #     oldpwd = self.cleaned_data.get('oldpwd')
    #     username = self.cleaned_data.get('username')
    #     user = User.objects.filter(username=username, password=oldpwd)
    #     if user:
    #         return self.cleaned_data
    #     raise ValidationError( "用户名或密码错误，请重新输入！")


class RegisterForm(forms.Form):
    username = forms.CharField(min_length=3,required=True,error_messages={
        'required':'用户名必须输入',
        'min_length':'用户名至少3个字符'
    })
    password = forms.CharField(min_length=3,required=True,error_messages={
        'required': '密码名必须输入',
        'min_length': '密码至少3个字符'
    })
    confirm = forms.CharField(min_length=3,required=True,error_messages={
        'required': '密码名必须输入',
        'min_length': '密码至少3个字符'
    })
    regtime = forms.DateTimeField(required=False,error_messages={
        'invalid':'日期格式错误',
    })
    # 单个字段验证: clean_xxxx
    def clean_password(self):
        password = self.cleaned_data.get('password')
        if password and password.isdigit():
            raise ValidationError("密码不能是纯数字")
        return password

    def clean_username(self):
        username = self.cleaned_data.get('username')
        print(username)
        users = User.objects.filter(username=username).first()
        print(users)
        if username == users:
            raise ValidationError("用户已存在，请重新输入")
        return username
    # 全局验证
    def clean(self):
        password = self.cleaned_data.get('password',None)
        confirm = self.cleaned_data.get('confirm','')
        print(password,confirm)
        if password != confirm:
            raise ValidationError({'confirm':"两次密码输入不一致"})
        return self.cleaned_data

# 登录验证
class LoginForm(forms.Form):
    # def __init__(self, data=None, files=None, auto_id='id_%s', prefix=None,
    #              initial=None, error_class=ErrorList, label_suffix=None,
    #              empty_permitted=False, field_order=None, use_required_attribute=None, renderer=None,request=None):
    #     super().__init__(data,files,auto_id,prefix,initial,error_class,label_suffix,empty_permitted,field_order,use_required_attribute,renderer,request)

    def clean(self):
        password = self.cleaned_data.get('password')
        username = self.cleaned_data.get('username')
        user = User.objects.filter(username=username,password=password)
        print(password,username)
        print(user)
        if user:
            return self.cleaned_data
        raise ValidationError("用户名或密码错误，请重新输入！")

DM_admin/App/views.py
import datetime
import os
import re
from random import randint
from time import time

from PIL import Image
from django.contrib.auth import authenticate, login, logout
from django.core.paginator import Paginator
from django.http import request, HttpResponse, response
from django.shortcuts import render, redirect
from django.urls import reverse

from App.forms import RegisterForm, ChangePwdForm, LoginForm
# from App.models import Category, Article, User, Mark
from App.models import User, GoodsType, Goods, OrderInfo, Brand
from App.yzm import vc
from DM_admin import settings

# 装饰器，路由保护
def check_login(func):
    def inner(*args,**kwargs):
        print(args,kwargs)
        if args[0].COOKIES.get('username'):
            return func(*args,**kwargs)
        else:
            return redirect('/loginb/')
    return inner

@check_login
def index(request):
    return render(request, 'index.html')

# 左边导航栏
# @check_login
def public_left(request):
    return render(request, "public_left.html")


# @check_login
def public_header(request):
    # 获取用户ｓｅｓｓｉｏｎ信息
    # user = request.session.get('user')
    # print(user)
    username = request.session.get('username')
    # print(username)
    return render(request, 'public_header.html',locals())


# 商品管理
# @check_login
def public_main(request, cid=-1, page=1):
    categories = GoodsType.objects.all()
    # 获取所有分类id
    postion = [cat.tid for cat in categories]
    if request.method == "POST":
        cid = int(request.POST.get('cid', -1))
        keyword = request.POST.get('keyword', '')
        # 文章检索
        articles = Goods.objects.filter(tid=cid, gtitle__icontains=keyword)
    else:
        # 检索分类
        if cid < 0:
            first_category = categories.first() # 查询第一个分类
            cid = first_category.tid  # 第一个分类的cid
        # 文章检索
        articles = Goods.objects.filter(tid=cid)
    pos = postion.index(cid)
    # 分页
    paginator = Paginator(articles, 6)
    # 分页对象
    # page表示当前页面
    pager = paginator.page(page)
    return render(request, "wenzhang_xinwen.html", locals())

# 订单管理
def xitong_set(request,uid=-1,page=1):
    username = request.session.get('username')
    users = User.objects.exclude(username=username)
    postion = [cat.uid for cat in users]
    if request.method == "POST":
        mid = int(request.POST.get('cid', -1))
        keyword = request.POST.get('keyword', '')
        # 评论检索
        marks = OrderInfo.objects.filter(uid=uid)
    else:
        # 检索分类
        if uid < 0:
            first_mark = users.first()  # 查询第一个分类
            print(first_mark)
            uid = first_mark.uid  # 第一个分类的cid
        # 文章检索
        marks = OrderInfo.objects.filter(uid=661)
    pos = postion.index(uid)
    # 分页
    paginator = Paginator(marks, 6)
    # 分页对象
    pager = paginator.page(page)
    return render(request,'xitong_set.html',locals())



# 用户管理
def tupian_pc_index(request,uid=1,page=1):
    users = User.objects.all()
    # 获取所有分类id
    postion = [cat.uid for cat in users]
    if request.method == "POST":
        uid = int(request.POST.get('uid', -1))
        keyword = request.POST.get('keyword', '')
        # 用户检索
        users = User.objects.filter(username__icontains=keyword)
    pos = postion.index(uid)
    # 分页
    # paginator = BaiduPaginator(articles, 1)
    # pager = paginator.page(page)
    # pager.page_range = paginator.custom_range(page,2)
    paginator = Paginator(users, 4)
    # 分页对象
    # page表示当前页面
    pager = paginator.page(page)
    return render(request,"user.html",locals())


def public_super_cg(request):
    return render(request,'public_super_cg.html')

# 商品发布
# @check_login
def wenzhang_xinwen_fabu(request):
    categories = GoodsType.objects.all()
    print(categories[0].type_name)
    if request.method == "POST":
        mcid = request.POST.get('cid')
        cid = GoodsType.objects.filter(tid=mcid).first()
        a_cid = cid.tid
        title = request.POST.get('title')
        content = request.POST.get('content')
        create_time = request.POST.get('create_time')
        picture = request.session.get('photo')
        gprice = request.POST.get('gprice')
        bid = Brand.objects.first()
        # 添加商品
        Goods.objects.create(gid=randint(1000, 9999),
                             gname=title,
                             gtitle=title,
                             gdescription=content,
                             gprice=gprice,
                             image=picture,
                             status=1, stock=1, gcolor=1, gsize=1,
                             bid=bid,
                             tid=cid
                             )
        return render(request, "wenzhang_xinwen_fabu.html", locals())
        # return redirect(reverse("App:main2", kwargs={'cid':a_cid,'page':1}))
    return render(request,"wenzhang_xinwen_fabu.html",locals())


# 辅助工具，注册用户
# @check_login
def user_register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            data.pop("confirm")
            # 把用户写入数据库
            # 密码会做签名，不能手动签名加密password
            user = User.objects.create_user(**data)
            if user:
                print(user.uid)
                return redirect('/tupian_pc_index/')
            else:
                return render(request, "register.html", {'form': form})
        else:
            return render(request, "register.html", {'form': form})
        # get请求
    return render(request, "register.html")

# 修改密码
# @check_login
def change_psw(request):
    # 查询当前登录用户
    username = request.session.get('username')
    # 检查旧密码是否一致
    if request.method == 'POST':
        oldpwd = request.POST.get('oldpwd')
        newpwd = request.POST.get('newpwd')
        # print(oldpwd,newpwd)
        user = authenticate(username=username,password=oldpwd)
        # print(user)
        form = ChangePwdForm(request.POST)
        if user and form.is_valid():
            data = form.cleaned_data
            data.pop("cfmpwd")
            user.set_password(newpwd)
            user.save()
            return render(request,"loginb.html",locals())
        else:
            return render(request, "change_psw.html", {'form': form,"msg": u"用户名或者密码错误!"})
    # else:
    #     return render(request, "change_psw.html")
    return render(request,"change_psw.html",locals())


# 退出/登录
def loginb(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        code = request.POST.get('code')
        vcode = request.session.get('vcode')
        # print(code,vcode)
        user = authenticate(username=username, password=password)
        # print('1222')
        # print(user)
        # form = LoginForm(request.POST)
        # if form.is_valid():
        if user and (code == vcode):
            # print('sfddfsds')
             # 使用ｓｅｓｓｉｏｎ记录用户登录信息
            request.session['username'] = username
            login(request,user)
            # print(username)
            return render(request, "index.html", locals())
            # return redirect(reverse("App:main2", kwargs={'cid': 1, 'page': 1}))
    return render(request, "loginb.html",{"msg": u"用户名或者密码错误!"})

def user_loginout(request):
    logout(request)
    return redirect('/loginb/')

#　验证码
def get_verify_img(req):
    result = vc.generate()
    # 把验证码字符串保存到session
    req.session['vcode'] = vc.code
    # print('vcode')
    print(vc.code)
    # 将缓存区的内容返回给前端
    return HttpResponse(result,'image/png')


# 文件上传
# @check_login
def upload(request):
    if request.method == 'POST':
        #　获取文件上传的对象
        fobj = request.FILES.get('photo')
        path = os.path.join(settings.STATICFILES_DIRS[0],'upload')
        path = os.path.join(path,fobj.name)
        if fobj:
            # print(fobj.name,fobj.size)
            with  open(path,'wb') as target:
                # 文件大于２．５ｍ
                if fobj.multiple_chunks():
                   for data in fobj.chunks():
                       target.write(data)
                else:
                    target.write(fobj.read())
            request.session['photo'] = path.replace('/var/www/data/Tblog', '')#/home/courage/Tblog

            return HttpResponse('上传成功'+path)
    return render(request,'image.html')

#　删除文章
# @check_login
def del_article(request,aid,cid=-1,page=1):
    article = Goods.objects.filter(gid=aid)
    if article:
        article.delete()
    return redirect(reverse("App:main2", kwargs={'cid':cid, 'page':page}))

# 商品修改
# @check_login
def wenzhang_xinwen_xiugai(request,aid,cid=1):
    categories = GoodsType.objects.all()
    article = Goods.objects.filter(gid=aid).first()
    print(article.image)
    if article:
        if request.method == "POST":
            mcid = request.POST['cid']
            cid = GoodsType.objects.filter(cid=mcid).first()
            article.tid = cid
            article.gid = aid
            article.gprice = request.POST['gprice']
            article.gtitle = request.POST['title']
            article.gdescription = request.POST['content']
            article.image =request.session.get('photo')
            article.save()
    return render(request,'wenzhang_xinwen_xiugai.html', locals())

# 修改用户信息
# @check_login
def change_user(request,uid):
    # 查询当前登录用户
    username = request.session.get('username')
    user = User.objects.filter(uid=uid).first()
    # 检查旧密码是否一致
    if request.method == 'POST':
        oldpwd = request.POST.get('oldpwd')
        newpwd = request.POST.get('newpwd')
        # print(oldpwd,newpwd)
        user = authenticate(username=user.username, password=oldpwd)
        # print(user)

DM_admin/templates/change_psw.html
{% load staticfiles %}
<!DOCTYPE html>
<html class=" js csstransforms3d">
<head>
	<meta charset="utf-8">
	<meta name="renderer" content="webkit">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>DM商城后台管理系统</title>
	<link rel="stylesheet" href="{% static 'css/base.css' %}">
	<link rel="stylesheet" href="{% static 'css/page.css' %}">
	<!--[if lte IE 8]>
	<link href="{% static 'css/ie8.css' %}" rel="stylesheet" type="text/css"/>
	<![endif]-->
	<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/modernizr.js' %}"></script>
	<!--[if IE]>
	<script src="http://libs.useso.com/js/html5shiv/3.7/html5shiv.min.js"></script>
	<![endif]-->
</head>

<body style="background: #f6f5fa;">
	<!--content S-->
	<div class="super-content">
		<div class="superCtab">
			<div class="publishArt">
                <table>
            <tr>
                <td>当前登录用户：</td>
                <td>{{ username }}</td>
                <td><a href="/loginb/">退出</a></td>
                <td><a href="{% url 'App:main' %}">用户中心</a></td>
            </tr>
        </table>
				<h4>修改密码</h4>
                <form action="" method="post">
                    {% csrf_token %}
                    <div class="pubMain">
					<h5 class="pubtitle">旧密码</h5>
					<div class="pub-txt-bar">
						<input type="password" name="oldpwd" class="shuruTxt shuruTxt2"><b class="error"></b>

						<div class="errorBox">{{msg}}</div>

					</div>
					<h5 class="pubtitle">新密码<span>（数字、字母、符号组合，最少8个字符）</span></h5>
					<div class="pub-txt-bar">
						<input type="password" name="newpwd" class="shuruTxt shuruTxt2"><b class="error"></b>
						<div class="errorBox">{{form.newpwd.errors}}</div>
					</div>
					<h5 class="pubtitle">确认密码</h5>
					<div class="pub-txt-bar">
						<input type="password"  name="cfmpwd" class="shuruTxt shuruTxt2"><b class="error"></b>
						<div class="errorBox">{{form.cfmpwd.errors}}</div>
					</div>
					<div class="pub-btn">
						<input type="submit" id="" value="确定" class="saveBtn">
						<input type="button" id="" value="重置" class="resetBtn">
					</div>
				</div>
                </form>

			</div>
		
		</div>
		<!--main-->
		
	</div>
	<!--content E-->
	


</body></html>

DM_admin/templates/image.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="{% url 'App:upload' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="photo"> <br>
    <input type="submit" value="确定上传">
</form>
</body>
</html>

DM_admin/templates/index.html

<!DOCTYPE html>
<html class=" js csstransforms3d"><head>
	<meta charset="utf-8">
	<meta name="renderer" content="webkit">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>DM商城后台管理系统</title>
	<link rel="stylesheet" href="/static/css/base.css">
	<link rel="stylesheet" href="/static/css/page.css">

	<script type="text/javascript" src="/static/js/jquery.min.js"></script>
	<script type="text/javascript" src="/static/js/modernizr.js"></script>

</head>

<body>
<div class="superWrap clearfix" style="height: 781px;">
	<!--side S-->
	<div class="super-side-menu">
		<iframe src="/left/" width="205" height="100%" marginheight="0" marginwidth="0" frameborder="0" scrolling="no"></iframe>
	</div>
	<!--side E-->
	<!--content S-->
	<div class="superContent">
		
		<div class="super-header super-header2">
			<iframe src="/header/" id="Pubheader" name="Pubheader" width="100%"  marginheight="0" marginwidth="0" frameborder="0" scrolling="no"></iframe>
		</div>
		<!--header-->
		<div class="superCtab superCtabBot" style="height: 695px;">
			<iframe src="/main/" id="Mainindex" name="Mainindex" width="100%" height="100%" marginheight="0" marginwidth="0" frameborder="0"></iframe>
		</div>
		<!--main-->
		
	</div>
	<!--content E-->
	
</div>

<script>
window.onresize = function(){
	var winH=$(window).height();
	var headH=$('.super-header').height();
	$('.superWrap').height(winH);
	$('.superCtabBot').height(winH-headH);
};
$(window).resize();
</script>

</body></html>

DM_admin/templates/loginb.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<meta name="renderer" content="webkit">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>用户登录</title>
	<link rel="stylesheet" href="{% static 'css/base.css' %}" />
	<link rel="stylesheet" href="{% static 'css/login.css' %}" />

</head>
<body>
<div class="superlogin"></div>
<div class="loginBox">
	<div class="loginMain">
		<div class="tabwrap">
            <form action="" method="post">
                {% csrf_token %}
                <table border="0" cellspacing="0" cellpadding="0">
			<tr><td class="title">用户名：</td><td><input type="text" name="username" class="form-control txt" /></td></tr>
			<tr><td class="title">密   码：</td><td><input type="password"  name="password" class="form-control txt" /></td></tr>
			<tr><td class="title">验证码：</td><td><input type="text" name="code" class="form-control txt txt2" /><span class="yzm"><img  id="mcode" name="vcode"onclick="change()" src='/get_verify_img'/></span>

</td></tr>

			<tr class="errortd"><td>&nbsp;</td><td><i class="ico-error"></i><span class="errorword">{{msg}}</span></td></tr>

			<tr><td>&nbsp;</td><td><input type="submit" style="background: #00843e; width: 102px; height: 42px; color: #fff; font-size: 16px; border-radius: 2px; " value="登录" />
                <input type="button" class="resetbtn" value="重置" onclick="location.href=''"/></td></tr>
			<tr><td>&nbsp;</td><td class="forgetpsw"></td></tr>
		</table>
            </form>

		</div>
	</div>
</div>
<div class="footer">Copyright © 2020-2021 jianet  All Rights Reserved.</div>
</body>

<script type="text/javascript" src="/static/js/jquery.min.js"></script>
<script>
function change() {
var url = "/get_verify_img?"+new Date().getTime()
$('#mcode').attr('src',url) //刷新验证码
}
</script>
</html>

DM_admin/templates/public_header.html
<!DOCTYPE html>
<html class=" js csstransforms3d"><head>
	<meta charset="utf-8">
	<meta name="renderer" content="webkit">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title></title>
	<link rel="stylesheet" href="/static/css/base.css">
	<link rel="stylesheet" href="/static/css/page.css">
	<!--[if lte IE 8]>
	<link href="css/ie8.css" rel="stylesheet" type="text/css"/>
	<![endif]-->
	<script type="text/javascript" src="/static/js/jquery.min.js"></script>
	<script type="text/javascript" src="/static/js/main.js"></script>
	<script type="text/javascript" src="/static/js/modernizr.js"></script>
	<!--[if IE]>
	<script src="http://libs.useso.com/js/html5shiv/3.7/html5shiv.min.js"></script>
	<![endif]-->
</head>

<body>
<div class="super-header clearfix">
	<h2>DM商城后台管理系统</h2>
	<div class="head-right">
		<i class="ico-user"></i>当前用户：
		<div class="userslideDown">
			<a href="javascript:;" class="superUser">{{ username }}<i class="ico-tri"></i></a>
			<div class="slidedownBox">
				<ul>
					<li><a href="{% url 'App:change_psw.html' %}" target="Mainindex">修改密码</a></li>
					<li><a href="{% url 'App:loginb.html' %}" target="_parent">退出</a></li>
				</ul>
			</div>
		</div>
	</div>
</div>
<!--header-->


</body></html>

DM_admin/templates/public_left.html
<!DOCTYPE html>
<html class=" js csstransforms3d"><head>
	<meta charset="utf-8">
	<meta name="renderer" content="webkit">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>公共侧边栏</title>
	<link rel="stylesheet" href="/static/css/base.css">
	<link rel="stylesheet" href="/static/css/page.css">
	<!--[if lte IE 8]>
	<link href="css/ie8.css" rel="stylesheet" type="text/css"/>
	<![endif]-->
	<script type="text/javascript" src="/static/js/jquery.min.js"></script>
	<script type="text/javascript" src="/static/js/main.js"></script>
	<script type="text/javascript" src="/static/js/modernizr.js"></script>
	<!--[if IE]>
	<script src="http://libs.useso.com/js/html5shiv/3.7/html5shiv.min.js"></script>
	<![endif]-->
</head>

<body>
	<!--side S-->
	<div class="super-side-menu">
		<div class="logo"><a href="public_super_cg.html" target="_parent"><img src="/static/images/logo.png"></a></div>
		
		<div class="side-menu">
			<ul>
				<li class=""><a href="{% url 'App:main' %}" target="Mainindex"><i class="ico-1"></i>商品管理</a></li>
{#				<li><a href="huodong_guanli.html" target="Mainindex"><i class="ico-2"></i>活动管理</a></li>#}
{#				<li class="on"><a href="xiangce_Guanli.html" target="Mainindex"><i class="ico-3"></i>相册管理</a></li>#}
				<li><a href="{% url 'App:tupian_pc_index' %}" target="Mainindex"><i class="ico-4"></i>用户管理</a></li>
{#				<li><a href="zixun_Team.html" target="Mainindex"><i class="ico-5"></i>咨询管理</a></li>#}
{#				<li><a href="muban_Guanli.html" target="Mainindex"><i class="ico-6"></i>模板管理</a></li>#}
				<li><a href="{% url 'App:xitong_set' %}" target="Mainindex"><i class="ico-7"></i>订单管理</a></li>
			</ul>
		</div>
	</div>
	<!--side E-->

<script type="text/javascript">
	$(function(){
		$('.side-menu li').click(function(){
			$(this).addClass('on').siblings().removeClass('on');
		})
	})
</script>

</body></html>