App/urls.py
from django.urls import path, include

from App import views
app_name='App'

urlpatterns = [
    #    path('admin/', admin.site.urls),
    path('index/',views.index,name='index'),

    path('category/<int:tid>/',views.category,name='category'),

    path('sale/<int:tid>/',views.sale,name='sale'),
    path('sale/',views.sale,name='sale'),

    path('details/',views.details,name='details'),
    path('details/<int:tid>/',views.details,name='details'),
    path('details/<int:tid>/<int:gid>/',views.details,name='details'),

    path('contact/',views.contact,name='contact'),

    path('handbags/<int:tid>/',views.handbags,name='handbags'),
    path('handbags/',views.handbags,name='handbags'),

    path('service/',views.service,name='service'),

    path('shoes/<int:tid>/', views.shoes, name='shoes'),
    path('shoes/',views.shoes,name='shoes'),

    path('wallents/<int:tid>/', views.wallents, name='wallents'),
    path('wallents/',views.wallents,name='wallents'),

    path('accessories/<int:tid>',views.accessories,name='accessories'),
    path('accessories/',views.accessories,name='accessories'),

    path('mans/<int:tid>/', views.mans, name='mans'),
    path('mans/<int:tid>/<int:page>/', views.mans, name='mans'),
    path('mans/', views.mans, name='mans'),

    path('news/<int:tid>/', views.news, name='news'),
    path('news/<int:tid>/<int:page>/', views.news, name='news'),
    path('news/', views.news, name='news'),

    path('logind/', views.loginb, name='login'),

    path('loginout/', views.loginout, name='loginout'),

    path('register/', views.register, name='register'),

    path('cart/', views.cart, name='cart'),
    path('cart/del/<int:gid>/', views.cart_del, name='cart_del'),

    path('palce_order/', views.palce_order, name='palce_order'),

    path('user_center_site/', views.user_center_site, name='user_center_site'),

    path('user_center_info/', views.user_center_info, name='user_center_info'),

    path('user_center_order/', views.user_center_order, name='user_center_order'),
    path('user_center_order/<int:page>/', views.user_center_order, name='user_center_order'),

    path('search/<str:keyword>/<int:page>/',views.search,name='serach'),

    path('add_goods/',views.add_goods,name='add_goods'),

# 文件上传
    path("upload/",views.upload,name='upload'),

]

DM/urls.py
# from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    #    path('admin/', admin.site.urls),
    path('', include('App.urls'))
]

DM_admin/DM_admin/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('',include('App.urls'))
]

templates/mans.html
<!DOCTYPE HTML>
<html>
<head>
<title>男士专区</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<!--<link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700' rel='stylesheet' type='text/css'>-->
<link href="/static/css/style.css" rel="stylesheet" type="text/css" media="all" />
<script src="/static/js/jquery.min.js"></script>
<!-- start top_js_button -->
<script type="text/javascript" src="/static/js/move-top.js"></script>
<script type="text/javascript" src="/static/js/easing.js"></script>
    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>
	<script src="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
   <script type="text/javascript">
		jQuery(document).ready(function($) {
			$(".scroll").click(function(event){
				event.preventDefault();
				$('html,body').animate({scrollTop:$(this.hash).offset().top},1200);
			});
		});
	</script>
</head>
<body>
<!-- start header -->
<div class="header_bg">
<div class="wrap">
	<div class="header">
		<div class="logo">
			<a href="{% url 'App:index' %}"><img src="/static/images/logo.png" alt=""/> </a>
		</div>
		<div class="h_icon">
		<ul class="icon1 sub-icon1">
			<li><a class="active-icon c1" href="{% url 'App:cart' %}"><i>￥{{ gprice }}</i></a>
			</li>
		</ul>
		</div>
		<div class="h_search">
    		<form action="#" method="post">
                {% csrf_token %}
    			<input type="text" value="" name="keyword" placeholder="输入标题关键字搜索">
                <input type="hidden" name="tid" value="{{ tid }}">
    			<input type="submit" value="">
    		</form>
		</div>
		<div class="clear"></div>
	</div>
</div>
</div>
<div class="header_btm">
<div class="wrap">
	<div class="header_sub">
		<div class="h_menu">
			<ul>
                <li><a href="{% url 'App:index' %}">首页</a></li> |
				<li class="active"><a href="{% url 'App:category' tid=tid %}">{{ good_type.type_name }}</a></li> |
				 {% for good_type in good_types %}
				<li><a href="{% url 'App:category' tid=good_type.tid %}">{{ good_type.type_name }}</a></li> |
				{% endfor %}
             <li><a href="{% url 'App:user_center_info'%}">用户中心</a></li> |
			</ul>
		</div>
		<div class="top-nav">
	          <nav class="nav">
	    	    <a href="#" id="w3-menu-trigger"> </a>
	                  <ul class="nav-list" style="">
	            	        <li class="nav-item"><a class="active" href="index.html">Home</a></li>
							{% for good_type in good_types %}
				<li><a href="{% url 'App:category' tid=good_type.tid %}">{{ good_type.type_name }}</a></li> |
				{% endfor %}
                       <li><a href="{% url 'App:user_center_info'%}">用户中心</a></li> |
	                 </ul>
	           </nav>
	             <div class="search_box">
				<form>
				   <input type="text" value="Search" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Search';}"><input type="submit" value="">
			    </form>
			</div>
	          <div class="clear"> </div>
	          <script src="/static/js/responsive.menu.js"></script>
         </div>
	<div class="clear"></div>
</div>
</div>
</div>
<!-- start main -->
<div class="main_bg">
<div class="wrap">
	<div class="main">
		<!-- start grids_of_3 -->
		<div class="grids_of_3">
             {% for bag in pager.object_list %}
			<div class="grid1_of_3">
				<a href="{% url 'App:details' tid=tid gid=bag.gid %}">
					<img src="{{ bag.image }}" alt=""/>
					<h3>{{ bag.gname }}</h3>
					<div class="price">
						<h4>￥{{ bag.gprice }}<span>点击购买</span></h4>
					</div>
					<span class="b_btm"></span>
				</a>
			</div>
             {% endfor %}
            <div class="clear"></div>
		</div>

	</div>
</div>
</div>
<div style="margin: 0 auto;border:0px solid #000;width:400px;height:100px">
    <ul class="pagination pagination-lg">
    <li><a href="{% url 'App:mans' tid=tid page=page|add:-1  %}" style="color: #3CC395">«</a></li>
    {% for page in paginator.page_range %}
    <li><a href="{% url 'App:mans' tid=tid page=page %}" style="color: #3CC395">{{ page }}</a></li>
        {% endfor %}
    <li><a href="{% url 'App:mans' tid=tid page=page|add:1%}" style="color: #3CC395">»</a></li>
  </ul>
</div>

<!-- start footer -->
<div class="footer_bg">
<div class="wrap">
	<div class="footer">
		<!-- start grids_of_4 -->
		<div class="grids_of_4">
			<div class="grid1_of_4">
				<h4>特色商品</h4>
				<ul class="f_nav">
                    {% for brand in feature_goods  %}
					<li><a href="{% url 'App:details' tid=1 gid=brand.gid %}">{{ brand.gname }}</a></li>
                    {% endfor %}
				</ul>
			</div>
			<div class="grid1_of_4">
				<h4>男士商店</h4>
				<ul class="f_nav">
					{% for man in mans  %}
					<li><a href="{% url 'App:details' tid=1 gid=man.gid %}">{{ man.gname }}</a></li>
                    {% endfor %}
				</ul>
			</div>
			<div class="grid1_of_4">
				<h4>女士商店</h4>
				<ul class="f_nav">
					{% for woman in womans  %}
					<li><a href="{% url 'App:details' tid=1 gid=woman.gid %}">{{ woman.gname }}</a></li>
                    {% endfor %}
				</ul>
			</div>
			<div class="grid1_of_4">
				<h4>品牌生活</h4>
				<ul class="f_nav">
					{% for brand in brands %}
					<li><a href="">{{ brand.bname }}</a></li>
                    {% endfor %}
				</ul>
			</div>
			<div class="clear"></div>
		</div>
	</div>
</div>
</div>
<!-- start footer -->
<div class="footer_bg1">
<div class="wrap">
	<div class="footer">
		<!-- scroll_top_btn -->
	    <script type="text/javascript">
			$(document).ready(function() {

				var defaults = {
		  			containerID: 'toTop', // fading element id
					containerHoverID: 'toTopHover', // fading element hover id
					scrollSpeed: 1200,
					easingType: 'linear'
		 		};


				$().UItoTop({ easingType: 'easeOutQuart' });

			});
		</script>
		 <a href="#" id="toTop" style="display: block;"><span id="toTopHover" style="opacity: 1;"></span></a>
		<!--end scroll_top_btn -->
		<div class="copy">
			<p class="link">Copyright &copy; 2020.Company name All rights reserved.<a target="_blank" href="#">DM</a></p>
		</div>
		<div class="clear"></div>
	</div>
</div>
</div>

</body>
</html>

templates/news.html
<!DOCTYPE HTML>
<html>
<head>
<title>男士专区</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<!--<link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700' rel='stylesheet' type='text/css'>-->
<link href="/static/css/style.css" rel="stylesheet" type="text/css" media="all" />
<script src="/static/js/jquery.min.js"></script>
<!-- start top_js_button -->
<script type="text/javascript" src="/static/js/move-top.js"></script>
<script type="text/javascript" src="/static/js/easing.js"></script>
    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>
	<script src="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
   <script type="text/javascript">
		jQuery(document).ready(function($) {
			$(".scroll").click(function(event){
				event.preventDefault();
				$('html,body').animate({scrollTop:$(this.hash).offset().top},1200);
			});
		});
	</script>
</head>
<body>
<!-- start header -->
<div class="header_bg">
<div class="wrap">
	<div class="header">
		<div class="logo">
			<a href="{% url 'App:index' %}"><img src="/static/images/logo.png" alt=""/> </a>
		</div>
		<div class="h_icon">
		<ul class="icon1 sub-icon1">
			<li><a class="active-icon c1" href="{% url 'App:cart' %}"><i>￥{{ gprice }}</i></a>
			</li>
		</ul>
		</div>
		<div class="h_search">
    		<form action="#" method="post">
                {% csrf_token %}
    			<input type="text" value="" name="keyword" placeholder="输入标题关键字搜索">
                <input type="hidden" name="tid" value="{{ tid }}">
    			<input type="submit" value="">
    		</form>
		</div>
		<div class="clear"></div>
	</div>
</div>
</div>
<div class="header_btm">
<div class="wrap">
	<div class="header_sub">
		<div class="h_menu">
			<ul>
                <li><a href="{% url 'App:index' %}">首页</a></li> |
				<li class="active"><a href="{% url 'App:category' tid=tid %}">{{ good_type.type_name }}</a></li> |
				 {% for good_type in good_types %}
				<li><a href="{% url 'App:category' tid=good_type.tid %}">{{ good_type.type_name }}</a></li> |
				{% endfor %}
             <li><a href="{% url 'App:user_center_info'%}">用户中心</a></li> |
			</ul>
		</div>
		<div class="top-nav">
	          <nav class="nav">
	    	    <a href="#" id="w3-menu-trigger"> </a>
	                  <ul class="nav-list" style="">
	            	        <li class="nav-item"><a class="active" href="index.html">Home</a></li>
							{% for good_type in good_types %}
				<li><a href="{% url 'App:category' tid=good_type.tid %}">{{ good_type.type_name }}</a></li> |
				{% endfor %}
                       <li><a href="{% url 'App:user_center_info'%}">用户中心</a></li> |
	                 </ul>
	           </nav>
	             <div class="search_box">
				<form>
				   <input type="text" value="Search" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Search';}"><input type="submit" value="">
			    </form>
			</div>
	          <div class="clear"> </div>
	          <script src="/static/js/responsive.menu.js"></script>
         </div>
	<div class="clear"></div>
</div>
</div>
</div>
<!-- start main -->
<div class="main_bg">
<div class="wrap">
	<div class="main">
		<!-- start grids_of_3 -->
		<div class="grids_of_3">
             {% for bag in pager.object_list %}
			<div class="grid1_of_3">
				<a href="{% url 'App:details' tid=tid gid=bag.gid  %}">
					<img src="{{ bag.image }}" alt=""/>
					<h3>{{ bag.gname }}</h3>
					<div class="price">
						<h4>￥{{ bag.gprice }}<span>点击购买</span></h4>
					</div>
					<span class="b_btm"></span>
				</a>
			</div>
             {% endfor %}
            <div class="clear"></div>
		</div>
	</div>
</div>
</div>
<div style="margin: 0 auto;border:0px solid #000;width:400px;height:100px">
    <ul class="pagination pagination-lg">
    <li><a href="{% url 'App:news' tid=tid page=page|add:-1  %}" style="color: #3CC395">«</a></li>
    {% for page in paginator.page_range %}
    <li><a href="{% url 'App:news' tid=tid page=page %}" style="color: #3CC395">{{ page }}</a></li>
        {% endfor %}
    <li><a href="{% url 'App:news' tid=tid page=page|add:1%}" style="color: #3CC395">»</a></li>
  </ul>
</div>

<!-- start footer -->
<div class="footer_bg">
<div class="wrap">
	<div class="footer">
		<!-- start grids_of_4 -->
		<div class="grids_of_4">
			<div class="grid1_of_4">
				<h4>特色商品</h4>
				<ul class="f_nav">
                    {% for brand in feature_goods  %}
					<li><a href="{% url 'App:details' tid=1 gid=brand.gid %}">{{ brand.gname }}</a></li>
                    {% endfor %}
				</ul>
			</div>
			<div class="grid1_of_4">
				<h4>男士商店</h4>
				<ul class="f_nav">
					{% for man in mans  %}
					<li><a href="{% url 'App:details' tid=1 gid=man.gid %}">{{ man.gname }}</a></li>
                    {% endfor %}
				</ul>
			</div>
			<div class="grid1_of_4">
				<h4>女士商店</h4>
				<ul class="f_nav">
					{% for woman in womans  %}
					<li><a href="{% url 'App:details' tid=1 gid=woman.gid %}">{{ woman.gname }}</a></li>
                    {% endfor %}
				</ul>
			</div>
			<div class="grid1_of_4">
				<h4>品牌生活</h4>
				<ul class="f_nav">
					{% for brand in brands %}
					<li><a href="">{{ brand.bname }}</a></li>
                    {% endfor %}
				</ul>
			</div>
			<div class="clear"></div>
		</div>
	</div>
</div>
</div>
<!-- start footer -->
<div class="footer_bg1">
<div class="wrap">
	<div class="footer">
		<!-- scroll_top_btn -->
	    <script type="text/javascript">
			$(document).ready(function() {

				var defaults = {
		  			containerID: 'toTop', // fading element id
					containerHoverID: 'toTopHover', // fading element hover id
					scrollSpeed: 1200,
					easingType: 'linear'
		 		};


				$().UItoTop({ easingType: 'easeOutQuart' });

			});
		</script>
		 <a href="#" id="toTop" style="display: block;"><span id="toTopHover" style="opacity: 1;"></span></a>
		<!--end scroll_top_btn -->
		<div class="copy">
			<p class="link">Copyright &copy; 2020.Company name All rights reserved.<a target="_blank" href="#">DM</a></p>
		</div>
		<div class="clear"></div>
	</div>
</div>
</div>

</body>
</html>

templates/place_order.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>提交订单</title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
    <link href="/static/css/style.css" rel="stylesheet" type="text/css" media="all" />
</head>
<body>
	<div class="header_con">
		<div class="header">
			<div class="welcome fl"><b style="color: #3CC395;font-size: 20px">{{ username }}</b>欢迎来到DM商城!</div>
			<div class="fr">
				<div class="login_btn fl">
					<a href="{% url 'App:loginout' %}">退出登录</a>
					<span>|</span>
					<a href="{% url 'App:register' %}">注册</a>
				</div>
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'App:user_center_info' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'App:cart' %}">我的购物车</a>
					<span>|</span>
					<a href="{% url 'App:user_center_order' page=1 %}">我的订单</a>
				</div>
			</div>
	</div>
	</div>

	<div class="search_bar clearfix">
		<a href="index.html" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;提交订单</div>
		<div class="h_search">
    		<form action="#" method="post">
                {% csrf_token %}
    			<input type="text" value="" name="keyword" placeholder="输入标题关键字搜索">
                <input type="hidden" name="tid" value="{{ tid }}">
    			<input type="submit" value="">
    		</form>
		</div>
	</div>
	<form action="" method="post">
    {% csrf_token %}
	<h3 class="common_title">确认收货地址</h3>
	<div class="common_list_con clearfix">
		<dl>
			<dt>寄送到：</dt>
			<dd><input type="radio" name="" checked="">{{ default_adds.addre }}－{{ default_adds.receiver }}－{{ default_adds.phone }}</dd>
		</dl>
		<a href="{% url 'App:user_center_site' %}" class="edit_site">编辑收货地址</a>
	</div>
	<h3 class="common_title">支付方式</h3>	
	<div class="common_list_con clearfix">
		<div class="pay_style_con clearfix">
			<input type="radio" name="pay_style" checked>
			<label class="cash">货到付款</label>
			<input type="radio" name="pay_style">
			<label class="zhifubao"></label>
		</div>
	</div>
	<h3 class="common_title">商品列表</h3>
	<div class="common_list_con clearfix">
		<ul class="goods_list_th clearfix">
			<li class="col01">商品名称</li>
			<li class="col02">商品单位</li>
			<li class="col03">商品价格</li>
			<li class="col04">数量</li>
			<li class="col05">小计</li>		
		</ul>
        {% for good in wating_pay_goods %}
		<ul class="goods_list_td clearfix">
			<li class="col01">{{ good.gid }}</li>
			<li class="col02"><img src="{{ good.image }}"></li>
			<li class="col03">{{good.gname}}</li>
			<li class="col04">件</li>
			<li class="col05">{{ good.gprice }}</li>
			<li class="col06">{{ good.goodnum }}</li>
			<li class="col07">{% widthratio  good.gprice  1  good.goodnum  %}</li>
		</ul>
        {% endfor %}
	</div>

	<h3 class="common_title">总金额结算</h3>
	<div class="common_list_con clearfix">
		<div class="settle_con">
			<div class="total_goods_count">共<em id="num">{{ wating_pay_counts }}</em>件商品，总金额<b id="total">{{ gprice }}元</b></div>
			<div class="transit">运费：<b>10元</b></div>
			<div class="total_pay">实付款：<b>{{ gprice|add:'10' }}元</b></div>
		</div>
	</div>

	<div class="order_submit clearfix">
        <input type="submit" id="order_btn" value="提交订单"/>
{#		<a href="javascript:;" id="order_btn" >提交订单</a>#}
	</div>	
    </form>>
	<div class="footer">
		<p class="link">Copyright &copy; 2020.Company name All rights reserved.<a target="_blank" href="#">DM</a></p>
	</div>

	<div class="popup_con">
		<div class="popup">
			<p>订单提交成功！</p>
		</div>
		
		<div class="mask"></div>
	</div>
	<script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
	<script type="text/javascript">
		$('#order_btn').click(function() {
			localStorage.setItem('order_finish',2);
			$('.popup_con').fadeIn('fast', function() {
				setTimeout(function(){
					$('.popup_con').fadeOut('fast',function(){
						window.location.href = '{% url 'App:index' %}';
					});	
				},3000)
				
			});
		});
	</script>
</body>
</html>

templates/user_center_order.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>用户中心</title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
    <link href="/static/css/style.css" rel="stylesheet" type="text/css" media="all" />
    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
</head>
<body>
	<div class="header_con">
		<div class="header">
            <div class="welcome fl"><b style="color: #3CC395;font-size: 20px">{{ username }}</b>欢迎来到DM商城!</div>
			<div class="fr">
				<div class="login_btn fl">
					<a href="{% url 'App:loginout' %}">退出登录</a>
					<span>|</span>
					<a href="{% url 'App:register' %}">注册</a>
				</div>
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'App:user_center_info' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'App:cart' %}">我的购物车</a>
					<span>|</span>
					<a href="{% url 'App:user_center_order' page=1 %}">我的订单</a>
				</div>
			</div>
		</div>		
	</div>

	<div class="search_bar clearfix">
		<a href="index.html" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		 <div class="h_search">
    		<form action="#" method="post">
                {% csrf_token %}
    			<input type="text" value="" name="keyword" placeholder="输入标题关键字搜索">
{#                <input type="hidden" name="tid" value="{{ tid }}">#}
    			<input type="submit" value="">
    		</form>
		</div>
	</div>

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'App:user_center_info' %}">· 个人信息</a></li>
				<li><a href="{% url 'App:user_center_order' %}"class="active">· 全部订单</a></li>
				<li><a href="{% url 'App:user_center_site' %}" >· 收货地址</a></li>
                <li><a href="{% url 'App:add_goods' %}" >· 发布上新</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">全部订单</h3>
            {% for info in orderinfo %}
				<ul class="order_list_th w978 clearfix">
					<li class="col01">{{ info.create_time }}</li>
					<li class="col02">订单号：{{ info.oid }}</li>
					<li class="col02 stress">{{info.order_status}}</li>
				</ul>
				<table class="order_list_table w980">

					<tbody>
						<tr>
							<td width="65%">

								<ul class="order_goods_list clearfix">					
{#									<li class="col01"><img src="/static/images/c2.jpg"></li>#}
{#									<li class="col02">嘎啦苹果嘎啦苹果<em>11.80元/500g</em></li>	#}
									<li class="col03" style="width: 30%">商品数量：{{ info.total_count }}</li>
									<li class="col04">商品总价：{{ info.total_price }}</li>
								</ul>

							</td>
							<td width="15%">待支付：{{ info.total_price }}元</td>
							<td width="15%">待付款</td>
							<td width="15%"><a href="#" class="oper_btn">去付款</a></td>
						</tr>
					</tbody>
				</table>
            {% endfor %}
		</div>

	</div>

<div style="margin: 0 auto;border:0px solid #000;width:400px;height:100px">
    <ul class="pagination pagination-lg">
    <li><a href="{% url 'App:user_center_order' page=page|add:-1  %}" style="color: #3CC395">«</a></li>
    {% for page in paginator.page_range %}
    <li><a href="{% url 'App:user_center_order' page=page %}" style="color: #3CC395">{{ page }}</a></li>
        {% endfor %}
    <li><a href="{% url 'App:user_center_order' page=page|add:1%}" style="color: #3CC395">»</a></li>
  </ul>
</div>


	<div class="footer">
		<p class="link">Copyright &copy; 2020.Company name All rights reserved.<a target="_blank" href="#">DM</a></p>
	</div>
	<script src="/static/js/jquery-1.12.4.min.js"></script>
    <script>
    $('.oper_btn').each(function () {
        // 获取支付状态
        status = $(this).attr('status')
        if (status == 1){
            $(this).text('去支付')
        }
        else if (status == 4){
            $(this).text('去评价')
        }
        else if (status == 5){
            $(this).text('已完成')
        }
    })

    $('.oper_btn').click(function () {
        // 获取status
        status = $(this).attr('status')
        // 获取订单id
        order_id = $(this).attr('order_id')
        if (status == 1){
            // 进行支付
            csrf = $('input[name="csrfmiddlewaretoken"]').val()
            // 组织参数
            params = {'order_id':order_id, 'csrfmiddlewaretoken':csrf}
            // 发起ajax post请求，访问/order/pay, 传递参数:order_id
            $.post('/order/pay', params, function (data) {
                if (data.res == 3){
                    // 引导用户到支付页面
                    window.open(data.pay_url)
                    // 浏览器访问/order/check, 获取支付交易的结果
                    // ajax post 传递参数:order_id
                    $.post('/order/check', params, function (data){
                        if (data.res == 3){
                            alert('支付成功')
                            // 刷新页面
                            location.reload()
                        }
                        else{
                            alert(data.errmsg)
                        }
                    })
                }
                else{
                    alert(data.errmsg)
                }
            })
        }
        else if (status == 4){
            // 其他情况
            // 跳转到评价页面
            location.href = '/order/comment/'+order_id
        }
    })
    </script>
</body>
</html>